### ISSUE TITLE
Certification Checklist

### ISSUE THREAD

**Issue by morgan-murray** [morgan-murray/bin-day#4]
To pass through the Alexa certification process, the following list of requirements should be met. Each ToDo list should be its own issue. The item here should only be ticked-off once all the items in the individual issue are completed and that issue is linked here.

- [x] Comply with policy requirements - see issue #5 
- [x] Comply with security requirements - see issue #6
- [x] Comply with functional testing requirements - see issue #7
- [x] Comply with voice interface and user experience requirements - see issue #8
